sonar.projectKey=contact-management-system
sonar.projectName=Contact Management System
sonar.projectVersion=1.0.0

sonar.sources=src/main/java,frontend/src
sonar.tests=src/test/java,frontend/src
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.source=17

sonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
sonar.exclusions=**/node_modules/**,**/target/**,**/build/**,**/*.spec.tsx

sonar.rules.profile=java-sonar-way
